/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: termsurf.proto */

#ifndef PROTOBUF_C_termsurf_2eproto__INCLUDED
#define PROTOBUF_C_termsurf_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Termsurf__TermSurfMessage Termsurf__TermSurfMessage;
typedef struct Termsurf__CreateTab Termsurf__CreateTab;
typedef struct Termsurf__CreateDevtoolsTab Termsurf__CreateDevtoolsTab;
typedef struct Termsurf__Resize Termsurf__Resize;
typedef struct Termsurf__CloseTab Termsurf__CloseTab;
typedef struct Termsurf__Navigate Termsurf__Navigate;
typedef struct Termsurf__MouseEvent Termsurf__MouseEvent;
typedef struct Termsurf__MouseMove Termsurf__MouseMove;
typedef struct Termsurf__ScrollEvent Termsurf__ScrollEvent;
typedef struct Termsurf__KeyEvent Termsurf__KeyEvent;
typedef struct Termsurf__FocusChanged Termsurf__FocusChanged;
typedef struct Termsurf__SetColorScheme Termsurf__SetColorScheme;
typedef struct Termsurf__ServerRegister Termsurf__ServerRegister;
typedef struct Termsurf__TabReady Termsurf__TabReady;
typedef struct Termsurf__CaContext Termsurf__CaContext;
typedef struct Termsurf__UrlChanged Termsurf__UrlChanged;
typedef struct Termsurf__LoadingState Termsurf__LoadingState;
typedef struct Termsurf__TitleChanged Termsurf__TitleChanged;
typedef struct Termsurf__CursorChanged Termsurf__CursorChanged;
typedef struct Termsurf__SetOverlay Termsurf__SetOverlay;
typedef struct Termsurf__SetDevtoolsOverlay Termsurf__SetDevtoolsOverlay;
typedef struct Termsurf__OpenSplit Termsurf__OpenSplit;
typedef struct Termsurf__ModeChanged Termsurf__ModeChanged;
typedef struct Termsurf__HelloRequest Termsurf__HelloRequest;
typedef struct Termsurf__HelloReply Termsurf__HelloReply;
typedef struct Termsurf__QueryLastRequest Termsurf__QueryLastRequest;
typedef struct Termsurf__QueryLastReply Termsurf__QueryLastReply;
typedef struct Termsurf__QueryDevtoolsRequest Termsurf__QueryDevtoolsRequest;
typedef struct Termsurf__QueryDevtoolsReply Termsurf__QueryDevtoolsReply;
typedef struct Termsurf__QueryTabsRequest Termsurf__QueryTabsRequest;
typedef struct Termsurf__TabInfo Termsurf__TabInfo;
typedef struct Termsurf__QueryTabsReply Termsurf__QueryTabsReply;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  TERMSURF__TERM_SURF_MESSAGE__MSG__NOT_SET = 0,
  TERMSURF__TERM_SURF_MESSAGE__MSG_CREATE_TAB = 1,
  TERMSURF__TERM_SURF_MESSAGE__MSG_CREATE_DEVTOOLS_TAB = 2,
  TERMSURF__TERM_SURF_MESSAGE__MSG_RESIZE = 3,
  TERMSURF__TERM_SURF_MESSAGE__MSG_CLOSE_TAB = 4,
  TERMSURF__TERM_SURF_MESSAGE__MSG_NAVIGATE = 5,
  TERMSURF__TERM_SURF_MESSAGE__MSG_MOUSE_EVENT = 6,
  TERMSURF__TERM_SURF_MESSAGE__MSG_MOUSE_MOVE = 7,
  TERMSURF__TERM_SURF_MESSAGE__MSG_SCROLL_EVENT = 8,
  TERMSURF__TERM_SURF_MESSAGE__MSG_KEY_EVENT = 9,
  TERMSURF__TERM_SURF_MESSAGE__MSG_FOCUS_CHANGED = 10,
  TERMSURF__TERM_SURF_MESSAGE__MSG_SET_COLOR_SCHEME = 11,
  TERMSURF__TERM_SURF_MESSAGE__MSG_SERVER_REGISTER = 12,
  TERMSURF__TERM_SURF_MESSAGE__MSG_TAB_READY = 13,
  TERMSURF__TERM_SURF_MESSAGE__MSG_CA_CONTEXT = 14,
  TERMSURF__TERM_SURF_MESSAGE__MSG_URL_CHANGED = 15,
  TERMSURF__TERM_SURF_MESSAGE__MSG_LOADING_STATE = 16,
  TERMSURF__TERM_SURF_MESSAGE__MSG_TITLE_CHANGED = 17,
  TERMSURF__TERM_SURF_MESSAGE__MSG_CURSOR_CHANGED = 18,
  TERMSURF__TERM_SURF_MESSAGE__MSG_SET_OVERLAY = 19,
  TERMSURF__TERM_SURF_MESSAGE__MSG_SET_DEVTOOLS_OVERLAY = 20,
  TERMSURF__TERM_SURF_MESSAGE__MSG_OPEN_SPLIT = 21,
  TERMSURF__TERM_SURF_MESSAGE__MSG_MODE_CHANGED = 22,
  TERMSURF__TERM_SURF_MESSAGE__MSG_HELLO_REQUEST = 23,
  TERMSURF__TERM_SURF_MESSAGE__MSG_HELLO_REPLY = 24,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_LAST_REQUEST = 25,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_LAST_REPLY = 26,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_DEVTOOLS_REQUEST = 27,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_DEVTOOLS_REPLY = 28,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_TABS_REQUEST = 29,
  TERMSURF__TERM_SURF_MESSAGE__MSG_QUERY_TABS_REPLY = 30
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TERMSURF__TERM_SURF_MESSAGE__MSG__CASE)
} Termsurf__TermSurfMessage__MsgCase;

/*
 * Wrapper — every message on the wire is one of these.
 */
struct  Termsurf__TermSurfMessage
{
  ProtobufCMessage base;
  Termsurf__TermSurfMessage__MsgCase msg_case;
  union {
    Termsurf__CaContext *ca_context;
    Termsurf__CloseTab *close_tab;
    Termsurf__CreateDevtoolsTab *create_devtools_tab;
    /*
     * Tab lifecycle (GUI → Chromium)
     */
    Termsurf__CreateTab *create_tab;
    Termsurf__CursorChanged *cursor_changed;
    /*
     * State (GUI → Chromium)
     */
    Termsurf__FocusChanged *focus_changed;
    Termsurf__HelloReply *hello_reply;
    /*
     * Request/reply pairs (TUI ↔ GUI)
     */
    Termsurf__HelloRequest *hello_request;
    Termsurf__KeyEvent *key_event;
    Termsurf__LoadingState *loading_state;
    /*
     * GUI → TUI
     */
    Termsurf__ModeChanged *mode_changed;
    /*
     * Input (GUI → Chromium)
     */
    Termsurf__MouseEvent *mouse_event;
    Termsurf__MouseMove *mouse_move;
    /*
     * Navigation (GUI → Chromium, TUI → GUI)
     */
    Termsurf__Navigate *navigate;
    Termsurf__OpenSplit *open_split;
    Termsurf__QueryDevtoolsReply *query_devtools_reply;
    Termsurf__QueryDevtoolsRequest *query_devtools_request;
    Termsurf__QueryLastReply *query_last_reply;
    Termsurf__QueryLastRequest *query_last_request;
    Termsurf__QueryTabsReply *query_tabs_reply;
    Termsurf__QueryTabsRequest *query_tabs_request;
    Termsurf__Resize *resize;
    Termsurf__ScrollEvent *scroll_event;
    /*
     * Chromium → GUI
     */
    Termsurf__ServerRegister *server_register;
    Termsurf__SetColorScheme *set_color_scheme;
    Termsurf__SetDevtoolsOverlay *set_devtools_overlay;
    /*
     * TUI → GUI
     */
    Termsurf__SetOverlay *set_overlay;
    Termsurf__TabReady *tab_ready;
    Termsurf__TitleChanged *title_changed;
    Termsurf__UrlChanged *url_changed;
  };
};
#define TERMSURF__TERM_SURF_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__term_surf_message__descriptor) \
, TERMSURF__TERM_SURF_MESSAGE__MSG__NOT_SET, {0} }


struct  Termsurf__CreateTab
{
  ProtobufCMessage base;
  char *url;
  char *pane_id;
  uint64_t pixel_width;
  uint64_t pixel_height;
  protobuf_c_boolean dark;
};
#define TERMSURF__CREATE_TAB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__create_tab__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  Termsurf__CreateDevtoolsTab
{
  ProtobufCMessage base;
  char *pane_id;
  int64_t inspected_tab_id;
  uint64_t pixel_width;
  uint64_t pixel_height;
  protobuf_c_boolean dark;
};
#define TERMSURF__CREATE_DEVTOOLS_TAB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__create_devtools_tab__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


struct  Termsurf__Resize
{
  ProtobufCMessage base;
  int64_t tab_id;
  uint64_t pixel_width;
  uint64_t pixel_height;
};
#define TERMSURF__RESIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__resize__descriptor) \
, 0, 0, 0 }


struct  Termsurf__CloseTab
{
  ProtobufCMessage base;
  int64_t tab_id;
};
#define TERMSURF__CLOSE_TAB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__close_tab__descriptor) \
, 0 }


struct  Termsurf__Navigate
{
  ProtobufCMessage base;
  /*
   * nonzero when GUI → Chromium
   */
  int64_t tab_id;
  /*
   * nonempty when TUI → GUI
   */
  char *pane_id;
  char *url;
};
#define TERMSURF__NAVIGATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__navigate__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__MouseEvent
{
  ProtobufCMessage base;
  int64_t tab_id;
  /*
   * "down" or "up"
   */
  char *type;
  /*
   * "left", "right", "middle"
   */
  char *button;
  double x;
  double y;
  int64_t click_count;
  uint64_t modifiers;
};
#define TERMSURF__MOUSE_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__mouse_event__descriptor) \
, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


struct  Termsurf__MouseMove
{
  ProtobufCMessage base;
  int64_t tab_id;
  double x;
  double y;
  uint64_t modifiers;
};
#define TERMSURF__MOUSE_MOVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__mouse_move__descriptor) \
, 0, 0, 0, 0 }


struct  Termsurf__ScrollEvent
{
  ProtobufCMessage base;
  int64_t tab_id;
  double x;
  double y;
  double delta_x;
  double delta_y;
  uint64_t phase;
  uint64_t momentum_phase;
  protobuf_c_boolean precise;
  uint64_t modifiers;
};
#define TERMSURF__SCROLL_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__scroll_event__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  Termsurf__KeyEvent
{
  ProtobufCMessage base;
  int64_t tab_id;
  /*
   * "down", "up", "repeat"
   */
  char *type;
  int64_t windows_key_code;
  char *utf8;
  uint64_t modifiers;
};
#define TERMSURF__KEY_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__key_event__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0 }


struct  Termsurf__FocusChanged
{
  ProtobufCMessage base;
  int64_t tab_id;
  protobuf_c_boolean focused;
};
#define TERMSURF__FOCUS_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__focus_changed__descriptor) \
, 0, 0 }


struct  Termsurf__SetColorScheme
{
  ProtobufCMessage base;
  /*
   * nonzero when GUI → Chromium
   */
  int64_t tab_id;
  /*
   * nonempty when TUI → GUI
   */
  char *pane_id;
  protobuf_c_boolean dark;
};
#define TERMSURF__SET_COLOR_SCHEME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__set_color_scheme__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0 }


struct  Termsurf__ServerRegister
{
  ProtobufCMessage base;
  char *profile;
};
#define TERMSURF__SERVER_REGISTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__server_register__descriptor) \
, (char *)protobuf_c_empty_string }


struct  Termsurf__TabReady
{
  ProtobufCMessage base;
  char *pane_id;
  int64_t tab_id;
};
#define TERMSURF__TAB_READY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__tab_ready__descriptor) \
, (char *)protobuf_c_empty_string, 0 }


struct  Termsurf__CaContext
{
  ProtobufCMessage base;
  int64_t tab_id;
  uint64_t ca_context_id;
  uint64_t pixel_width;
  uint64_t pixel_height;
};
#define TERMSURF__CA_CONTEXT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__ca_context__descriptor) \
, 0, 0, 0, 0 }


struct  Termsurf__UrlChanged
{
  ProtobufCMessage base;
  int64_t tab_id;
  char *url;
};
#define TERMSURF__URL_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__url_changed__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Termsurf__LoadingState
{
  ProtobufCMessage base;
  int64_t tab_id;
  /*
   * "loading", "progress", "done", "error"
   */
  char *state;
  /*
   * 0-100
   */
  uint64_t progress;
};
#define TERMSURF__LOADING_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__loading_state__descriptor) \
, 0, (char *)protobuf_c_empty_string, 0 }


struct  Termsurf__TitleChanged
{
  ProtobufCMessage base;
  int64_t tab_id;
  char *title;
};
#define TERMSURF__TITLE_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__title_changed__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Termsurf__CursorChanged
{
  ProtobufCMessage base;
  int64_t tab_id;
  int64_t cursor_type;
};
#define TERMSURF__CURSOR_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__cursor_changed__descriptor) \
, 0, 0 }


struct  Termsurf__SetOverlay
{
  ProtobufCMessage base;
  char *pane_id;
  uint64_t col;
  uint64_t row;
  uint64_t width;
  uint64_t height;
  char *url;
  char *profile;
  protobuf_c_boolean browsing;
};
#define TERMSURF__SET_OVERLAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__set_overlay__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Termsurf__SetDevtoolsOverlay
{
  ProtobufCMessage base;
  char *pane_id;
  uint64_t col;
  uint64_t row;
  uint64_t width;
  uint64_t height;
  char *profile;
  protobuf_c_boolean browsing;
  int64_t inspected_tab_id;
};
#define TERMSURF__SET_DEVTOOLS_OVERLAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__set_devtools_overlay__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string, 0, 0 }


struct  Termsurf__OpenSplit
{
  ProtobufCMessage base;
  char *pane_id;
  /*
   * "horizontal" or "vertical"
   */
  char *direction;
  char *command;
};
#define TERMSURF__OPEN_SPLIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__open_split__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__ModeChanged
{
  ProtobufCMessage base;
  protobuf_c_boolean browsing;
};
#define TERMSURF__MODE_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__mode_changed__descriptor) \
, 0 }


struct  Termsurf__HelloRequest
{
  ProtobufCMessage base;
  char *pane_id;
};
#define TERMSURF__HELLO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__hello_request__descriptor) \
, (char *)protobuf_c_empty_string }


struct  Termsurf__HelloReply
{
  ProtobufCMessage base;
  char *homepage;
};
#define TERMSURF__HELLO_REPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__hello_reply__descriptor) \
, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryLastRequest
{
  ProtobufCMessage base;
  char *pane_id;
  char *profile;
};
#define TERMSURF__QUERY_LAST_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_last_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryLastReply
{
  ProtobufCMessage base;
  char *pane_id;
  int64_t tab_id;
  char *profile;
  char *error;
};
#define TERMSURF__QUERY_LAST_REPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_last_reply__descriptor) \
, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryDevtoolsRequest
{
  ProtobufCMessage base;
  char *pane_id;
  int64_t inspected_tab_id;
  char *profile;
};
#define TERMSURF__QUERY_DEVTOOLS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_devtools_request__descriptor) \
, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryDevtoolsReply
{
  ProtobufCMessage base;
  int64_t tab_id;
  char *error;
};
#define TERMSURF__QUERY_DEVTOOLS_REPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_devtools_reply__descriptor) \
, 0, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryTabsRequest
{
  ProtobufCMessage base;
  char *pane_id;
  char *profile;
};
#define TERMSURF__QUERY_TABS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_tabs_request__descriptor) \
, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__TabInfo
{
  ProtobufCMessage base;
  int64_t id;
  int64_t inspected_tab_id;
  char *pane_id;
  char *url;
};
#define TERMSURF__TAB_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__tab_info__descriptor) \
, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Termsurf__QueryTabsReply
{
  ProtobufCMessage base;
  int64_t gui_panes;
  int64_t chromium_tabs;
  int64_t chromium_browser;
  int64_t chromium_devtools;
  size_t n_tabs;
  Termsurf__TabInfo **tabs;
  char *error;
};
#define TERMSURF__QUERY_TABS_REPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__query_tabs_reply__descriptor) \
, 0, 0, 0, 0, 0,NULL, (char *)protobuf_c_empty_string }


/* Termsurf__TermSurfMessage methods */
void   termsurf__term_surf_message__init
                     (Termsurf__TermSurfMessage         *message);
size_t termsurf__term_surf_message__get_packed_size
                     (const Termsurf__TermSurfMessage   *message);
size_t termsurf__term_surf_message__pack
                     (const Termsurf__TermSurfMessage   *message,
                      uint8_t             *out);
size_t termsurf__term_surf_message__pack_to_buffer
                     (const Termsurf__TermSurfMessage   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__TermSurfMessage *
       termsurf__term_surf_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__term_surf_message__free_unpacked
                     (Termsurf__TermSurfMessage *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__CreateTab methods */
void   termsurf__create_tab__init
                     (Termsurf__CreateTab         *message);
size_t termsurf__create_tab__get_packed_size
                     (const Termsurf__CreateTab   *message);
size_t termsurf__create_tab__pack
                     (const Termsurf__CreateTab   *message,
                      uint8_t             *out);
size_t termsurf__create_tab__pack_to_buffer
                     (const Termsurf__CreateTab   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__CreateTab *
       termsurf__create_tab__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__create_tab__free_unpacked
                     (Termsurf__CreateTab *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__CreateDevtoolsTab methods */
void   termsurf__create_devtools_tab__init
                     (Termsurf__CreateDevtoolsTab         *message);
size_t termsurf__create_devtools_tab__get_packed_size
                     (const Termsurf__CreateDevtoolsTab   *message);
size_t termsurf__create_devtools_tab__pack
                     (const Termsurf__CreateDevtoolsTab   *message,
                      uint8_t             *out);
size_t termsurf__create_devtools_tab__pack_to_buffer
                     (const Termsurf__CreateDevtoolsTab   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__CreateDevtoolsTab *
       termsurf__create_devtools_tab__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__create_devtools_tab__free_unpacked
                     (Termsurf__CreateDevtoolsTab *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__Resize methods */
void   termsurf__resize__init
                     (Termsurf__Resize         *message);
size_t termsurf__resize__get_packed_size
                     (const Termsurf__Resize   *message);
size_t termsurf__resize__pack
                     (const Termsurf__Resize   *message,
                      uint8_t             *out);
size_t termsurf__resize__pack_to_buffer
                     (const Termsurf__Resize   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__Resize *
       termsurf__resize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__resize__free_unpacked
                     (Termsurf__Resize *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__CloseTab methods */
void   termsurf__close_tab__init
                     (Termsurf__CloseTab         *message);
size_t termsurf__close_tab__get_packed_size
                     (const Termsurf__CloseTab   *message);
size_t termsurf__close_tab__pack
                     (const Termsurf__CloseTab   *message,
                      uint8_t             *out);
size_t termsurf__close_tab__pack_to_buffer
                     (const Termsurf__CloseTab   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__CloseTab *
       termsurf__close_tab__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__close_tab__free_unpacked
                     (Termsurf__CloseTab *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__Navigate methods */
void   termsurf__navigate__init
                     (Termsurf__Navigate         *message);
size_t termsurf__navigate__get_packed_size
                     (const Termsurf__Navigate   *message);
size_t termsurf__navigate__pack
                     (const Termsurf__Navigate   *message,
                      uint8_t             *out);
size_t termsurf__navigate__pack_to_buffer
                     (const Termsurf__Navigate   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__Navigate *
       termsurf__navigate__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__navigate__free_unpacked
                     (Termsurf__Navigate *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__MouseEvent methods */
void   termsurf__mouse_event__init
                     (Termsurf__MouseEvent         *message);
size_t termsurf__mouse_event__get_packed_size
                     (const Termsurf__MouseEvent   *message);
size_t termsurf__mouse_event__pack
                     (const Termsurf__MouseEvent   *message,
                      uint8_t             *out);
size_t termsurf__mouse_event__pack_to_buffer
                     (const Termsurf__MouseEvent   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__MouseEvent *
       termsurf__mouse_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__mouse_event__free_unpacked
                     (Termsurf__MouseEvent *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__MouseMove methods */
void   termsurf__mouse_move__init
                     (Termsurf__MouseMove         *message);
size_t termsurf__mouse_move__get_packed_size
                     (const Termsurf__MouseMove   *message);
size_t termsurf__mouse_move__pack
                     (const Termsurf__MouseMove   *message,
                      uint8_t             *out);
size_t termsurf__mouse_move__pack_to_buffer
                     (const Termsurf__MouseMove   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__MouseMove *
       termsurf__mouse_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__mouse_move__free_unpacked
                     (Termsurf__MouseMove *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__ScrollEvent methods */
void   termsurf__scroll_event__init
                     (Termsurf__ScrollEvent         *message);
size_t termsurf__scroll_event__get_packed_size
                     (const Termsurf__ScrollEvent   *message);
size_t termsurf__scroll_event__pack
                     (const Termsurf__ScrollEvent   *message,
                      uint8_t             *out);
size_t termsurf__scroll_event__pack_to_buffer
                     (const Termsurf__ScrollEvent   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__ScrollEvent *
       termsurf__scroll_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__scroll_event__free_unpacked
                     (Termsurf__ScrollEvent *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__KeyEvent methods */
void   termsurf__key_event__init
                     (Termsurf__KeyEvent         *message);
size_t termsurf__key_event__get_packed_size
                     (const Termsurf__KeyEvent   *message);
size_t termsurf__key_event__pack
                     (const Termsurf__KeyEvent   *message,
                      uint8_t             *out);
size_t termsurf__key_event__pack_to_buffer
                     (const Termsurf__KeyEvent   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__KeyEvent *
       termsurf__key_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__key_event__free_unpacked
                     (Termsurf__KeyEvent *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__FocusChanged methods */
void   termsurf__focus_changed__init
                     (Termsurf__FocusChanged         *message);
size_t termsurf__focus_changed__get_packed_size
                     (const Termsurf__FocusChanged   *message);
size_t termsurf__focus_changed__pack
                     (const Termsurf__FocusChanged   *message,
                      uint8_t             *out);
size_t termsurf__focus_changed__pack_to_buffer
                     (const Termsurf__FocusChanged   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__FocusChanged *
       termsurf__focus_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__focus_changed__free_unpacked
                     (Termsurf__FocusChanged *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__SetColorScheme methods */
void   termsurf__set_color_scheme__init
                     (Termsurf__SetColorScheme         *message);
size_t termsurf__set_color_scheme__get_packed_size
                     (const Termsurf__SetColorScheme   *message);
size_t termsurf__set_color_scheme__pack
                     (const Termsurf__SetColorScheme   *message,
                      uint8_t             *out);
size_t termsurf__set_color_scheme__pack_to_buffer
                     (const Termsurf__SetColorScheme   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__SetColorScheme *
       termsurf__set_color_scheme__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__set_color_scheme__free_unpacked
                     (Termsurf__SetColorScheme *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__ServerRegister methods */
void   termsurf__server_register__init
                     (Termsurf__ServerRegister         *message);
size_t termsurf__server_register__get_packed_size
                     (const Termsurf__ServerRegister   *message);
size_t termsurf__server_register__pack
                     (const Termsurf__ServerRegister   *message,
                      uint8_t             *out);
size_t termsurf__server_register__pack_to_buffer
                     (const Termsurf__ServerRegister   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__ServerRegister *
       termsurf__server_register__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__server_register__free_unpacked
                     (Termsurf__ServerRegister *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__TabReady methods */
void   termsurf__tab_ready__init
                     (Termsurf__TabReady         *message);
size_t termsurf__tab_ready__get_packed_size
                     (const Termsurf__TabReady   *message);
size_t termsurf__tab_ready__pack
                     (const Termsurf__TabReady   *message,
                      uint8_t             *out);
size_t termsurf__tab_ready__pack_to_buffer
                     (const Termsurf__TabReady   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__TabReady *
       termsurf__tab_ready__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__tab_ready__free_unpacked
                     (Termsurf__TabReady *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__CaContext methods */
void   termsurf__ca_context__init
                     (Termsurf__CaContext         *message);
size_t termsurf__ca_context__get_packed_size
                     (const Termsurf__CaContext   *message);
size_t termsurf__ca_context__pack
                     (const Termsurf__CaContext   *message,
                      uint8_t             *out);
size_t termsurf__ca_context__pack_to_buffer
                     (const Termsurf__CaContext   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__CaContext *
       termsurf__ca_context__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__ca_context__free_unpacked
                     (Termsurf__CaContext *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__UrlChanged methods */
void   termsurf__url_changed__init
                     (Termsurf__UrlChanged         *message);
size_t termsurf__url_changed__get_packed_size
                     (const Termsurf__UrlChanged   *message);
size_t termsurf__url_changed__pack
                     (const Termsurf__UrlChanged   *message,
                      uint8_t             *out);
size_t termsurf__url_changed__pack_to_buffer
                     (const Termsurf__UrlChanged   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__UrlChanged *
       termsurf__url_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__url_changed__free_unpacked
                     (Termsurf__UrlChanged *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__LoadingState methods */
void   termsurf__loading_state__init
                     (Termsurf__LoadingState         *message);
size_t termsurf__loading_state__get_packed_size
                     (const Termsurf__LoadingState   *message);
size_t termsurf__loading_state__pack
                     (const Termsurf__LoadingState   *message,
                      uint8_t             *out);
size_t termsurf__loading_state__pack_to_buffer
                     (const Termsurf__LoadingState   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__LoadingState *
       termsurf__loading_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__loading_state__free_unpacked
                     (Termsurf__LoadingState *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__TitleChanged methods */
void   termsurf__title_changed__init
                     (Termsurf__TitleChanged         *message);
size_t termsurf__title_changed__get_packed_size
                     (const Termsurf__TitleChanged   *message);
size_t termsurf__title_changed__pack
                     (const Termsurf__TitleChanged   *message,
                      uint8_t             *out);
size_t termsurf__title_changed__pack_to_buffer
                     (const Termsurf__TitleChanged   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__TitleChanged *
       termsurf__title_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__title_changed__free_unpacked
                     (Termsurf__TitleChanged *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__CursorChanged methods */
void   termsurf__cursor_changed__init
                     (Termsurf__CursorChanged         *message);
size_t termsurf__cursor_changed__get_packed_size
                     (const Termsurf__CursorChanged   *message);
size_t termsurf__cursor_changed__pack
                     (const Termsurf__CursorChanged   *message,
                      uint8_t             *out);
size_t termsurf__cursor_changed__pack_to_buffer
                     (const Termsurf__CursorChanged   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__CursorChanged *
       termsurf__cursor_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__cursor_changed__free_unpacked
                     (Termsurf__CursorChanged *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__SetOverlay methods */
void   termsurf__set_overlay__init
                     (Termsurf__SetOverlay         *message);
size_t termsurf__set_overlay__get_packed_size
                     (const Termsurf__SetOverlay   *message);
size_t termsurf__set_overlay__pack
                     (const Termsurf__SetOverlay   *message,
                      uint8_t             *out);
size_t termsurf__set_overlay__pack_to_buffer
                     (const Termsurf__SetOverlay   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__SetOverlay *
       termsurf__set_overlay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__set_overlay__free_unpacked
                     (Termsurf__SetOverlay *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__SetDevtoolsOverlay methods */
void   termsurf__set_devtools_overlay__init
                     (Termsurf__SetDevtoolsOverlay         *message);
size_t termsurf__set_devtools_overlay__get_packed_size
                     (const Termsurf__SetDevtoolsOverlay   *message);
size_t termsurf__set_devtools_overlay__pack
                     (const Termsurf__SetDevtoolsOverlay   *message,
                      uint8_t             *out);
size_t termsurf__set_devtools_overlay__pack_to_buffer
                     (const Termsurf__SetDevtoolsOverlay   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__SetDevtoolsOverlay *
       termsurf__set_devtools_overlay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__set_devtools_overlay__free_unpacked
                     (Termsurf__SetDevtoolsOverlay *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__OpenSplit methods */
void   termsurf__open_split__init
                     (Termsurf__OpenSplit         *message);
size_t termsurf__open_split__get_packed_size
                     (const Termsurf__OpenSplit   *message);
size_t termsurf__open_split__pack
                     (const Termsurf__OpenSplit   *message,
                      uint8_t             *out);
size_t termsurf__open_split__pack_to_buffer
                     (const Termsurf__OpenSplit   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__OpenSplit *
       termsurf__open_split__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__open_split__free_unpacked
                     (Termsurf__OpenSplit *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__ModeChanged methods */
void   termsurf__mode_changed__init
                     (Termsurf__ModeChanged         *message);
size_t termsurf__mode_changed__get_packed_size
                     (const Termsurf__ModeChanged   *message);
size_t termsurf__mode_changed__pack
                     (const Termsurf__ModeChanged   *message,
                      uint8_t             *out);
size_t termsurf__mode_changed__pack_to_buffer
                     (const Termsurf__ModeChanged   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__ModeChanged *
       termsurf__mode_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__mode_changed__free_unpacked
                     (Termsurf__ModeChanged *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__HelloRequest methods */
void   termsurf__hello_request__init
                     (Termsurf__HelloRequest         *message);
size_t termsurf__hello_request__get_packed_size
                     (const Termsurf__HelloRequest   *message);
size_t termsurf__hello_request__pack
                     (const Termsurf__HelloRequest   *message,
                      uint8_t             *out);
size_t termsurf__hello_request__pack_to_buffer
                     (const Termsurf__HelloRequest   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__HelloRequest *
       termsurf__hello_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__hello_request__free_unpacked
                     (Termsurf__HelloRequest *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__HelloReply methods */
void   termsurf__hello_reply__init
                     (Termsurf__HelloReply         *message);
size_t termsurf__hello_reply__get_packed_size
                     (const Termsurf__HelloReply   *message);
size_t termsurf__hello_reply__pack
                     (const Termsurf__HelloReply   *message,
                      uint8_t             *out);
size_t termsurf__hello_reply__pack_to_buffer
                     (const Termsurf__HelloReply   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__HelloReply *
       termsurf__hello_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__hello_reply__free_unpacked
                     (Termsurf__HelloReply *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryLastRequest methods */
void   termsurf__query_last_request__init
                     (Termsurf__QueryLastRequest         *message);
size_t termsurf__query_last_request__get_packed_size
                     (const Termsurf__QueryLastRequest   *message);
size_t termsurf__query_last_request__pack
                     (const Termsurf__QueryLastRequest   *message,
                      uint8_t             *out);
size_t termsurf__query_last_request__pack_to_buffer
                     (const Termsurf__QueryLastRequest   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryLastRequest *
       termsurf__query_last_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_last_request__free_unpacked
                     (Termsurf__QueryLastRequest *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryLastReply methods */
void   termsurf__query_last_reply__init
                     (Termsurf__QueryLastReply         *message);
size_t termsurf__query_last_reply__get_packed_size
                     (const Termsurf__QueryLastReply   *message);
size_t termsurf__query_last_reply__pack
                     (const Termsurf__QueryLastReply   *message,
                      uint8_t             *out);
size_t termsurf__query_last_reply__pack_to_buffer
                     (const Termsurf__QueryLastReply   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryLastReply *
       termsurf__query_last_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_last_reply__free_unpacked
                     (Termsurf__QueryLastReply *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryDevtoolsRequest methods */
void   termsurf__query_devtools_request__init
                     (Termsurf__QueryDevtoolsRequest         *message);
size_t termsurf__query_devtools_request__get_packed_size
                     (const Termsurf__QueryDevtoolsRequest   *message);
size_t termsurf__query_devtools_request__pack
                     (const Termsurf__QueryDevtoolsRequest   *message,
                      uint8_t             *out);
size_t termsurf__query_devtools_request__pack_to_buffer
                     (const Termsurf__QueryDevtoolsRequest   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryDevtoolsRequest *
       termsurf__query_devtools_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_devtools_request__free_unpacked
                     (Termsurf__QueryDevtoolsRequest *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryDevtoolsReply methods */
void   termsurf__query_devtools_reply__init
                     (Termsurf__QueryDevtoolsReply         *message);
size_t termsurf__query_devtools_reply__get_packed_size
                     (const Termsurf__QueryDevtoolsReply   *message);
size_t termsurf__query_devtools_reply__pack
                     (const Termsurf__QueryDevtoolsReply   *message,
                      uint8_t             *out);
size_t termsurf__query_devtools_reply__pack_to_buffer
                     (const Termsurf__QueryDevtoolsReply   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryDevtoolsReply *
       termsurf__query_devtools_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_devtools_reply__free_unpacked
                     (Termsurf__QueryDevtoolsReply *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryTabsRequest methods */
void   termsurf__query_tabs_request__init
                     (Termsurf__QueryTabsRequest         *message);
size_t termsurf__query_tabs_request__get_packed_size
                     (const Termsurf__QueryTabsRequest   *message);
size_t termsurf__query_tabs_request__pack
                     (const Termsurf__QueryTabsRequest   *message,
                      uint8_t             *out);
size_t termsurf__query_tabs_request__pack_to_buffer
                     (const Termsurf__QueryTabsRequest   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryTabsRequest *
       termsurf__query_tabs_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_tabs_request__free_unpacked
                     (Termsurf__QueryTabsRequest *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__TabInfo methods */
void   termsurf__tab_info__init
                     (Termsurf__TabInfo         *message);
size_t termsurf__tab_info__get_packed_size
                     (const Termsurf__TabInfo   *message);
size_t termsurf__tab_info__pack
                     (const Termsurf__TabInfo   *message,
                      uint8_t             *out);
size_t termsurf__tab_info__pack_to_buffer
                     (const Termsurf__TabInfo   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__TabInfo *
       termsurf__tab_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__tab_info__free_unpacked
                     (Termsurf__TabInfo *message,
                      ProtobufCAllocator *allocator);
/* Termsurf__QueryTabsReply methods */
void   termsurf__query_tabs_reply__init
                     (Termsurf__QueryTabsReply         *message);
size_t termsurf__query_tabs_reply__get_packed_size
                     (const Termsurf__QueryTabsReply   *message);
size_t termsurf__query_tabs_reply__pack
                     (const Termsurf__QueryTabsReply   *message,
                      uint8_t             *out);
size_t termsurf__query_tabs_reply__pack_to_buffer
                     (const Termsurf__QueryTabsReply   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__QueryTabsReply *
       termsurf__query_tabs_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__query_tabs_reply__free_unpacked
                     (Termsurf__QueryTabsReply *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Termsurf__TermSurfMessage_Closure)
                 (const Termsurf__TermSurfMessage *message,
                  void *closure_data);
typedef void (*Termsurf__CreateTab_Closure)
                 (const Termsurf__CreateTab *message,
                  void *closure_data);
typedef void (*Termsurf__CreateDevtoolsTab_Closure)
                 (const Termsurf__CreateDevtoolsTab *message,
                  void *closure_data);
typedef void (*Termsurf__Resize_Closure)
                 (const Termsurf__Resize *message,
                  void *closure_data);
typedef void (*Termsurf__CloseTab_Closure)
                 (const Termsurf__CloseTab *message,
                  void *closure_data);
typedef void (*Termsurf__Navigate_Closure)
                 (const Termsurf__Navigate *message,
                  void *closure_data);
typedef void (*Termsurf__MouseEvent_Closure)
                 (const Termsurf__MouseEvent *message,
                  void *closure_data);
typedef void (*Termsurf__MouseMove_Closure)
                 (const Termsurf__MouseMove *message,
                  void *closure_data);
typedef void (*Termsurf__ScrollEvent_Closure)
                 (const Termsurf__ScrollEvent *message,
                  void *closure_data);
typedef void (*Termsurf__KeyEvent_Closure)
                 (const Termsurf__KeyEvent *message,
                  void *closure_data);
typedef void (*Termsurf__FocusChanged_Closure)
                 (const Termsurf__FocusChanged *message,
                  void *closure_data);
typedef void (*Termsurf__SetColorScheme_Closure)
                 (const Termsurf__SetColorScheme *message,
                  void *closure_data);
typedef void (*Termsurf__ServerRegister_Closure)
                 (const Termsurf__ServerRegister *message,
                  void *closure_data);
typedef void (*Termsurf__TabReady_Closure)
                 (const Termsurf__TabReady *message,
                  void *closure_data);
typedef void (*Termsurf__CaContext_Closure)
                 (const Termsurf__CaContext *message,
                  void *closure_data);
typedef void (*Termsurf__UrlChanged_Closure)
                 (const Termsurf__UrlChanged *message,
                  void *closure_data);
typedef void (*Termsurf__LoadingState_Closure)
                 (const Termsurf__LoadingState *message,
                  void *closure_data);
typedef void (*Termsurf__TitleChanged_Closure)
                 (const Termsurf__TitleChanged *message,
                  void *closure_data);
typedef void (*Termsurf__CursorChanged_Closure)
                 (const Termsurf__CursorChanged *message,
                  void *closure_data);
typedef void (*Termsurf__SetOverlay_Closure)
                 (const Termsurf__SetOverlay *message,
                  void *closure_data);
typedef void (*Termsurf__SetDevtoolsOverlay_Closure)
                 (const Termsurf__SetDevtoolsOverlay *message,
                  void *closure_data);
typedef void (*Termsurf__OpenSplit_Closure)
                 (const Termsurf__OpenSplit *message,
                  void *closure_data);
typedef void (*Termsurf__ModeChanged_Closure)
                 (const Termsurf__ModeChanged *message,
                  void *closure_data);
typedef void (*Termsurf__HelloRequest_Closure)
                 (const Termsurf__HelloRequest *message,
                  void *closure_data);
typedef void (*Termsurf__HelloReply_Closure)
                 (const Termsurf__HelloReply *message,
                  void *closure_data);
typedef void (*Termsurf__QueryLastRequest_Closure)
                 (const Termsurf__QueryLastRequest *message,
                  void *closure_data);
typedef void (*Termsurf__QueryLastReply_Closure)
                 (const Termsurf__QueryLastReply *message,
                  void *closure_data);
typedef void (*Termsurf__QueryDevtoolsRequest_Closure)
                 (const Termsurf__QueryDevtoolsRequest *message,
                  void *closure_data);
typedef void (*Termsurf__QueryDevtoolsReply_Closure)
                 (const Termsurf__QueryDevtoolsReply *message,
                  void *closure_data);
typedef void (*Termsurf__QueryTabsRequest_Closure)
                 (const Termsurf__QueryTabsRequest *message,
                  void *closure_data);
typedef void (*Termsurf__TabInfo_Closure)
                 (const Termsurf__TabInfo *message,
                  void *closure_data);
typedef void (*Termsurf__QueryTabsReply_Closure)
                 (const Termsurf__QueryTabsReply *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor termsurf__term_surf_message__descriptor;
extern const ProtobufCMessageDescriptor termsurf__create_tab__descriptor;
extern const ProtobufCMessageDescriptor termsurf__create_devtools_tab__descriptor;
extern const ProtobufCMessageDescriptor termsurf__resize__descriptor;
extern const ProtobufCMessageDescriptor termsurf__close_tab__descriptor;
extern const ProtobufCMessageDescriptor termsurf__navigate__descriptor;
extern const ProtobufCMessageDescriptor termsurf__mouse_event__descriptor;
extern const ProtobufCMessageDescriptor termsurf__mouse_move__descriptor;
extern const ProtobufCMessageDescriptor termsurf__scroll_event__descriptor;
extern const ProtobufCMessageDescriptor termsurf__key_event__descriptor;
extern const ProtobufCMessageDescriptor termsurf__focus_changed__descriptor;
extern const ProtobufCMessageDescriptor termsurf__set_color_scheme__descriptor;
extern const ProtobufCMessageDescriptor termsurf__server_register__descriptor;
extern const ProtobufCMessageDescriptor termsurf__tab_ready__descriptor;
extern const ProtobufCMessageDescriptor termsurf__ca_context__descriptor;
extern const ProtobufCMessageDescriptor termsurf__url_changed__descriptor;
extern const ProtobufCMessageDescriptor termsurf__loading_state__descriptor;
extern const ProtobufCMessageDescriptor termsurf__title_changed__descriptor;
extern const ProtobufCMessageDescriptor termsurf__cursor_changed__descriptor;
extern const ProtobufCMessageDescriptor termsurf__set_overlay__descriptor;
extern const ProtobufCMessageDescriptor termsurf__set_devtools_overlay__descriptor;
extern const ProtobufCMessageDescriptor termsurf__open_split__descriptor;
extern const ProtobufCMessageDescriptor termsurf__mode_changed__descriptor;
extern const ProtobufCMessageDescriptor termsurf__hello_request__descriptor;
extern const ProtobufCMessageDescriptor termsurf__hello_reply__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_last_request__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_last_reply__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_devtools_request__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_devtools_reply__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_tabs_request__descriptor;
extern const ProtobufCMessageDescriptor termsurf__tab_info__descriptor;
extern const ProtobufCMessageDescriptor termsurf__query_tabs_reply__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_termsurf_2eproto__INCLUDED */
