// Generates the config-option and keybind-action reference pages from the
// Ghostboard fork's `ghostty.5.md` man page (emitted by the fork's mdgen build
// step). Output is committed to the repo and consumed by the Astro build, so
// the website never needs the fork at build time — mirroring Ghostty's own
// `make sync-webdata` model.
//
// Usage (from website/):
//   bun run gen:references            # regenerate the committed pages
//   bun run gen:references --check    # exit 1 if committed output is stale
//   GHOSTTY_DOC=/path/to/ghostty.5.md bun run gen:references
//   bun run gen:references --in /path/to/ghostty.5.md

import fs from "fs";
import path from "path";
import GithubSlugger from "github-slugger";

const __dirname = path.dirname(new URL(import.meta.url).pathname);
const websiteDir = path.resolve(__dirname, "..");

const args = process.argv.slice(2);
const checkMode = args.includes("--check");

function parseArg(flag: string): string | undefined {
  const i = args.indexOf(flag);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : undefined;
}

const inputPath = path.resolve(
  websiteDir,
  parseArg("--in") ??
    process.env.GHOSTTY_DOC ??
    "../ghostboard/zig-out/share/ghostty/doc/ghostty.5.md",
);

if (!fs.existsSync(inputPath)) {
  console.error(
    `gen-references: man page not found at ${inputPath}\n` +
      `Build the Ghostboard docs first (the fork emits ` +
      `zig-out/share/ghostty/doc/ghostty.5.md), or pass --in <path> / set ` +
      `GHOSTTY_DOC.`,
  );
  process.exit(1);
}

const HEADER_RE = /^\*\*`(.+?)`\*\*\s*$/;
const SECTION_RE = /^# /;

interface Entry {
  name: string;
  /** De-indented body lines, or null for a bodyless (grouped variant) entry. */
  body: string[] | null;
}

/**
 * Parse the entries in the half-open line range [start, end) of `lines`.
 * Each `**`name`**` header begins an entry; its body is the following lines up
 * to the next header (or the end of the range). A body whose lines are all
 * blank marks a bodyless entry. Bodied lines are de-indented by stripping the
 * leading 4 columns (the `:   ` marker on the first line, 4-space indentation
 * on the rest), preserving relative indentation for nested code/lists.
 */
function parseEntries(lines: string[], start: number, end: number): Entry[] {
  const entries: Entry[] = [];
  let current: { name: string; raw: string[] } | null = null;

  const flush = () => {
    if (!current) return;
    // Trim leading/trailing blank lines from the raw body.
    let { raw } = current;
    while (raw.length && raw[0].trim() === "") raw = raw.slice(1);
    while (raw.length && raw[raw.length - 1].trim() === "") raw = raw.slice(0, -1);
    if (raw.length === 0) {
      entries.push({ name: current.name, body: null });
    } else {
      // Strip the leading 4 columns from every line (clamped for short lines).
      const body = raw.map((l) => l.slice(4));
      entries.push({ name: current.name, body });
    }
    current = null;
  };

  for (let i = start; i < end; i++) {
    const line = lines[i];
    const m = line.match(HEADER_RE);
    if (m) {
      flush();
      current = { name: m[1], raw: [] };
    } else if (current) {
      current.raw.push(line);
    }
  }
  flush();
  return entries;
}

function findHeading(lines: string[], heading: string): number {
  return lines.findIndex((l) => l.trim() === heading);
}

function renderPage(
  frontmatter: Record<string, string>,
  lead: string,
  entries: Entry[],
): string {
  const slugger = new GithubSlugger();
  // Pre-compute the slug for every entry name in document order, matching how
  // Astro slugs headings on the rendered page (so anchor links resolve).
  const slugOf = new Map<string, string>();
  for (const e of entries) slugOf.set(e.name, slugger.slug(e.name));

  // Track the most recent bodied entry so bodyless variants can link to it.
  let lastBodied: string | null = null;

  const out: string[] = [];
  out.push("---");
  for (const [k, v] of Object.entries(frontmatter)) out.push(`${k}: ${v}`);
  out.push("---");
  out.push("");
  out.push(
    "<!-- GENERATED by scripts/gen-references.ts from the Ghostboard fork's " +
      "ghostty.5.md. Do not edit by hand; run `bun run gen:references`. -->",
  );
  out.push("");
  out.push(`# ${frontmatter.title}`);
  out.push("");
  out.push(lead);
  out.push("");

  for (const e of entries) {
    out.push(`## \`${e.name}\``);
    out.push("");
    if (e.body) {
      // Each entry is an <h2>. Demote any headings inside the body (the man
      // page uses `##` subsections like "Chained Actions" within the keybind
      // option) by two levels so they nest under the entry instead of looking
      // like sibling entries. `#` only matches at column 0; indented `#` inside
      // code blocks is untouched.
      out.push(
        ...e.body.map((l) =>
          l.replace(
            /^(#{1,6}) /,
            (_m, h: string) => "#".repeat(Math.min(h.length + 2, 6)) + " ",
          ),
        ),
      );
      lastBodied = e.name;
    } else if (lastBodied) {
      out.push(`See [\`${lastBodied}\`](#${slugOf.get(lastBodied)}).`);
    } else {
      // No preceding bodied entry to link to (does not occur in the current
      // artifact); emit the heading alone rather than a dangling link.
    }
    out.push("");
  }

  // Normalize trailing whitespace to a single final newline.
  return out.join("\n").replace(/\n+$/, "") + "\n";
}

const raw = fs.readFileSync(inputPath, "utf8");
const lines = raw.split("\n");

const configStart = findHeading(lines, "# CONFIGURATION OPTIONS");
const keybindStart = findHeading(lines, "# KEYBIND ACTIONS");
const filesStart = findHeading(lines, "# FILES");

if (configStart < 0 || keybindStart < 0 || filesStart < 0) {
  console.error(
    "gen-references: could not find expected section headings " +
      "(# CONFIGURATION OPTIONS / # KEYBIND ACTIONS / # FILES) in the man page. " +
      "The fork's mdgen output format may have changed.",
  );
  process.exit(1);
}

const configEntries = parseEntries(lines, configStart + 1, keybindStart);
const keybindEntries = parseEntries(lines, keybindStart + 1, filesStart);

const configPage = renderPage(
  {
    title: "Configuration Options",
    navLabel: "Config Options",
    description:
      "Complete reference for every Ghostboard configuration option, generated from the TermSurf fork.",
    section: "Configuration",
    order: "2",
  },
  "Every configuration option, generated from the TermSurf Ghostboard fork's " +
    "`ghostty.5.md`. See [Configuration](/docs/reference/configuration) for the " +
    "config file location and the TermSurf-specific settings.",
  configEntries,
);

const keybindPage = renderPage(
  {
    title: "Keybind Actions",
    navLabel: "Keybind Actions",
    description:
      "Every keybind action available to the keybind configuration option, generated from the TermSurf fork.",
    section: "Configuration",
    order: "3",
  },
  "Every action that can be bound with the `keybind` configuration option, " +
    "generated from the TermSurf Ghostboard fork's `ghostty.5.md`.",
  keybindEntries,
);

const outputs: { file: string; content: string; count: number }[] = [
  {
    file: path.resolve(websiteDir, "src/content/docs/reference/config.md"),
    content: configPage,
    count: configEntries.length,
  },
  {
    file: path.resolve(
      websiteDir,
      "src/content/docs/reference/keybind-actions.md",
    ),
    content: keybindPage,
    count: keybindEntries.length,
  },
];

if (checkMode) {
  let stale = false;
  for (const { file, content } of outputs) {
    const existing = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    if (existing !== content) {
      console.error(`gen-references --check: stale or missing ${path.relative(websiteDir, file)}`);
      stale = true;
    }
  }
  if (stale) {
    console.error("Run `bun run gen:references` and commit the result.");
    process.exit(1);
  }
  console.log("gen-references --check: committed reference pages are up to date.");
  process.exit(0);
}

for (const { file, content, count } of outputs) {
  fs.writeFileSync(file, content);
  console.log(`gen-references: wrote ${path.relative(websiteDir, file)} (${count} entries)`);
}
