#!/usr/bin/env python3
"""Inventory pinned Ghostty and Roastty config option names.

This is intentionally a bounded source extractor, not a general Zig or Rust
parser. It only reads the source regions relevant to Issue 805 Experiment 6:
Ghostty's top-level Config fields, Ghostty's compatibility map, and Roastty's
pub(crate) Config fields.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
from pathlib import Path


FIELD_RE = re.compile(r'^(?P<name>@"[^"]+"|[A-Za-z_][A-Za-z0-9_]*):')
ALIAS_RE = re.compile(r'^\s*\.\{\s*"(?P<alias>[^"]+)"\s*,')
RUST_DOC_KEY_RE = re.compile(r"^\s*/// `(?P<key>[^`]+)`\.")
RUST_FIELD_RE = re.compile(r"^\s*pub\s+(?P<field>[A-Za-z_][A-Za-z0-9_]*)\s*:")


@dataclasses.dataclass(frozen=True)
class Inventory:
    upstream: list[str]
    aliases: list[str]
    internal: list[str]
    roastty: list[str]

    @property
    def missing(self) -> list[str]:
        return sorted(set(self.upstream) - set(self.roastty))

    @property
    def extra(self) -> list[str]:
        return sorted(set(self.roastty) - set(self.upstream))

    @property
    def represented(self) -> list[str]:
        return sorted(set(self.upstream) & set(self.roastty))


def normalize_zig_field(raw: str) -> str:
    if raw.startswith('@"') and raw.endswith('"'):
        return raw[2:-1]
    return raw.replace("_", "-")


def extract_ghostty(path: Path) -> tuple[list[str], list[str], list[str]]:
    aliases: list[str] = []
    fields: list[str] = []
    internal: list[str] = []
    in_compatibility = False
    in_config_fields = False

    for line in path.read_text().splitlines():
        if line.startswith("pub const compatibility"):
            in_compatibility = True
            continue

        if in_compatibility:
            match = ALIAS_RE.match(line)
            if match:
                aliases.append(match.group("alias"))
                continue
            if line.startswith("});"):
                in_compatibility = False
                in_config_fields = True
                continue
            continue

        if in_config_fields and line.startswith("pub fn "):
            break

        if not in_config_fields:
            continue

        match = FIELD_RE.match(line)
        if not match:
            continue

        raw = match.group("name")
        name = normalize_zig_field(raw)
        if raw.startswith("_") or name.startswith("_"):
            internal.append(raw if raw.startswith("_") else name)
            continue
        fields.append(name)

    return sorted(set(fields)), sorted(set(aliases)), sorted(set(internal))


def extract_roastty(path: Path) -> list[str]:
    keys: list[str] = []
    pending_docs: list[str] = []
    in_config = False
    depth = 0

    for line in path.read_text().splitlines():
        if line.startswith("pub(crate) struct Config {"):
            in_config = True
            depth = 1
            continue

        if not in_config:
            continue

        depth += line.count("{") - line.count("}")
        if depth <= 0:
            break

        doc_match = RUST_DOC_KEY_RE.match(line)
        if doc_match:
            pending_docs.append(doc_match.group("key"))
            continue

        if RUST_FIELD_RE.match(line) and pending_docs:
            keys.extend(pending_docs)
            pending_docs = []
            continue

        if line.strip() and not line.strip().startswith("///"):
            pending_docs = []

    return sorted(set(keys))


def markdown_list(values: list[str]) -> str:
    if not values:
        return "- None.\n"
    return "\n".join(f"- `{value}`" for value in values) + "\n"


def emit_inventory(inventory: Inventory, output: Path) -> None:
    content = f"""# Config Inventory

Generated by `issues/0805-roastty-ghostty-parity/config_inventory.py` for
Issue 805 Experiment 6.

## Counts

| Category | Count |
| --- | ---: |
| Ghostty canonical config options | {len(inventory.upstream)} |
| Ghostty compatibility aliases | {len(inventory.aliases)} |
| Ghostty private/internal fields | {len(inventory.internal)} |
| Roastty documented config options | {len(inventory.roastty)} |
| Canonical options represented by Roastty | {len(inventory.represented)} |
| Canonical options missing from Roastty | {len(inventory.missing)} |
| Roastty-only options | {len(inventory.extra)} |

## Extraction Boundaries

- Upstream canonical options are top-level fields in
  `vendor/ghostty/src/config/Config.zig` after `pub const compatibility` and
  before the first `pub fn`.
- Compatibility aliases are entries in Ghostty's static `compatibility` map.
- Private/internal Ghostty fields are counted for audit completeness but are not
  user config options.
- Roastty options are documented field keys in
  `roastty/src/config/mod.rs` inside `pub(crate) struct Config`.

## Ghostty Canonical Options

{markdown_list(inventory.upstream)}
## Ghostty Compatibility Aliases

{markdown_list(inventory.aliases)}
## Ghostty Private/Internal Fields

{markdown_list(inventory.internal)}
## Roastty Options

{markdown_list(inventory.roastty)}
## Missing Canonical Options

{markdown_list(inventory.missing)}
## Roastty-Only Options

{markdown_list(inventory.extra)}
## Classification Notes

- Represented canonical options are tracked as inventory coverage rows in
  `config-matrix.md`. Broader behavior proof is tracked by explicit facet rows.
- Missing canonical options are `Gap` because Roastty cannot have parity for an
  option it does not represent.
- Compatibility aliases are tracked separately from canonical options.
- Private/internal Ghostty fields are not ordinary user config options and do
  not receive config matrix rows in this experiment.
"""
    output.write_text(content)


def matrix_row(row_id: int, option: str, status: str, notes: str) -> str:
    return (
        f"| CFG-{row_id:03d} | canonical option `{option}` | Ghostty canonical "
        f"config option `{option}` in `vendor/ghostty/src/config/Config.zig`. "
        f"| Roastty documents the same canonical config option in "
        f"`roastty/src/config/mod.rs`. | {status} | Static inventory plus "
        f"default formatter/parser guards. | "
        f"`issues/0805-roastty-ghostty-parity/config-inventory.md`; "
        f"`issues/0805-roastty-ghostty-parity/default-config-oracle.md` "
        f"| Tier 0 | `python3 issues/0805-roastty-ghostty-parity/config_inventory.py "
        f"--upstream vendor/ghostty/src/config/Config.zig --roastty "
        f"roastty/src/config/mod.rs --output "
        f"issues/0805-roastty-ghostty-parity/config-inventory.md --matrix "
        f"issues/0805-roastty-ghostty-parity/config-matrix.md`; "
        f"`cargo test --manifest-path roastty/Cargo.toml "
        f"config_default_format_oracle config_default_parser_oracle` | When "
        f"config fields change or before closing Issue 805. | Inventory catches "
        f"name coverage drift; default guards prove the represented option appears "
        f"in the pinned default formatter/parser surface. | Experiment 12 "
        f"| {notes} |\n"
    )


def alias_row(row_id: int, alias: str) -> str:
    return (
        f"| CFG-{row_id:03d} | compatibility alias `{alias}` | Ghostty "
        f"compatibility alias `{alias}` in `vendor/ghostty/src/config/Config.zig`. "
        f"| Roastty compatibility map entry is proven by focused parser tests. "
        f"| Pass | `cargo test --manifest-path roastty/Cargo.toml "
        f"config_compatibility_alias` | "
        f"`logs/issue805-exp7-config-compatibility-alias-test.log` | Tier 1 | "
        f"`cargo test --manifest-path roastty/Cargo.toml "
        f"config_compatibility_alias` | On config parser changes and before "
        f"closing Issue 805. | Focused unit tests prove parser effects for all "
        f"eight Ghostty compatibility entries. | Experiment 7 | Compatibility "
        f"semantics proven; runtime effects remain covered by canonical option "
        f"facet rows. |\n"
    )


def default_and_facet_rows(start_id: int) -> list[str]:
    rows = [
        (
            "Default config format oracle, full surface",
            "Ghostty `+show-config --default --no-pager` prints default config values in formatter order.",
            "Roastty `Config::default().format_config(...)` matches every normalized default config line after app-name normalization.",
            "Pass",
            "Fixture-backed unit test plus A/B log comparison.",
            "`issues/0805-roastty-ghostty-parity/default-config-oracle.md`; `logs/issue805-exp10-roastty-default-config.txt`; `logs/issue805-exp10-default-config-diff-summary.txt`",
            "Tier 1",
            "`cargo test --manifest-path roastty/Cargo.toml config_default_format_oracle`",
            "On config formatter/default changes and before closing Issue 805.",
            "The fixture test compares exact ordered default output for all 635 normalized default config lines.",
            "Experiment 10",
            "This does not prove non-default formatter behavior, diagnostics, precedence, reload, UI, or runtime-effect parity.",
        ),
        (
            "Default `keybind` format and contents",
            "Ghostty emits 93 normalized default `keybind` lines from the pinned default config output.",
            "Roastty emits the same 93 normalized default `keybind` lines in the same order.",
            "Pass",
            "Fixture-backed unit test compares exact ordered keybind output.",
            "`issues/0805-roastty-ghostty-parity/default-config-oracle.md`; `logs/issue805-exp9-default-config-oracle.log`; `logs/issue805-exp9-default-config-diff-summary.txt`",
            "Tier 1",
            "`cargo test --manifest-path roastty/Cargo.toml config_default_format_oracle`",
            "On keybinding/config formatter changes and before closing Issue 805.",
            "The guard proves default keybind config formatting and content only; parser/runtime behavior remains covered separately.",
            "Experiment 9",
            "Default keybind formatter parity is proven; general keybind behavior is not.",
        ),
        (
            "Default `command-palette-entry` format",
            "Ghostty emits 88 normalized default `command-palette-entry` lines from the pinned default config output.",
            "Roastty emits the same 88 normalized default `command-palette-entry` lines in the same order.",
            "Pass",
            "Fixture-backed unit test compares exact ordered command-palette output.",
            "`issues/0805-roastty-ghostty-parity/default-config-oracle.md`; `logs/issue805-exp10-roastty-default-config.txt`; `logs/issue805-exp10-default-config-diff-summary.txt`",
            "Tier 1",
            "`cargo test --manifest-path roastty/Cargo.toml config_default_format_oracle`",
            "On command-palette/config formatter changes and before closing Issue 805.",
            "The guard proves default command-palette config formatting and content only; UI dispatch and runtime behavior remain covered separately.",
            "Experiment 10",
            "Default command-palette formatter parity is proven; general command-palette behavior is not.",
        ),
        (
            "Default config parser oracle",
            "Ghostty `+show-config --default --no-pager` output is documented by Ghostty as valid config-file format.",
            "Roastty accepts all 635 pinned Ghostty default config lines through its config-line parser and per-key parser.",
            "Pass",
            "Fixture-backed unit test parses every default config line independently.",
            "`issues/0805-roastty-ghostty-parity/default-config-oracle.md`; `issues/0805-roastty-ghostty-parity/11-default-config-parser-oracle.md`",
            "Tier 1",
            "`cargo test --manifest-path roastty/Cargo.toml config_default_parser_oracle`",
            "On config parser/default formatter changes and before closing Issue 805.",
            "The guard proves default-line parser acceptance and names the rejected line/key on failure.",
            "Experiment 11",
            "This does not prove non-default values, whole-file repeatable replacement semantics, diagnostics, precedence, reload, UI, or runtime effects.",
        ),
        (
            "Non-default parser semantics",
            "Ghostty parsers accept and reject the full range of documented non-default values for every canonical option.",
            "Roastty has focused parser tests for many option families, but this issue has not yet proven full non-default parser parity across all canonical options.",
            "Gap",
            "Explicit follow-up parser parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 1",
            "TBD by future parser parity experiments.",
            "Before closing Issue 805.",
            "The default parser oracle proves only default-line acceptance, not the non-default value space.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Non-default formatter behavior and order",
            "Ghostty formats configured non-default values and repeatable values with stable text and ordering.",
            "Roastty has proven default formatter parity but not every non-default formatter form.",
            "Gap",
            "Explicit follow-up formatter parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 1",
            "TBD by future formatter parity experiments.",
            "Before closing Issue 805.",
            "The default formatter oracle proves only the default surface.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Invalid-value diagnostics",
            "Ghostty reports diagnostics for invalid config values with expected line/key behavior.",
            "Roastty has focused diagnostic tests for some options, but full diagnostic parity is not proven.",
            "Gap",
            "Explicit follow-up diagnostic parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 1",
            "TBD by future diagnostic parity experiments.",
            "Before closing Issue 805.",
            "Default parser acceptance does not exercise invalid values.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Validation and finalization behavior",
            "Ghostty finalizes config values using platform/runtime context, including validation and derived defaults.",
            "Roastty has focused finalization behavior in code, but full validation/finalization parity is not proven.",
            "Gap",
            "Explicit follow-up finalization parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 1",
            "TBD by future validation/finalization parity experiments.",
            "Before closing Issue 805.",
            "Name/default parser guards do not prove finalize-time behavior.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Config source precedence and repeated-file load semantics",
            "Ghostty applies defaults, config files, CLI args, repeatable values, and repeated config-file loads with documented precedence.",
            "Roastty implements load paths, but full precedence and repeatable replacement parity is not proven.",
            "Gap",
            "Explicit follow-up precedence/load parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 2",
            "TBD by future config load parity experiments.",
            "Before closing Issue 805.",
            "Per-line parser acceptance does not prove whole-file or source precedence semantics.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Config reload behavior",
            "Ghostty reloads config and applies reloadable changes while preserving or rejecting non-reloadable state as designed.",
            "Roastty reload behavior has not been fully audited against pinned Ghostty.",
            "Gap",
            "Explicit follow-up reload parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`",
            "Tier 2",
            "TBD by future config reload parity experiments.",
            "Before closing Issue 805.",
            "Parser/formatter parity does not prove live reload behavior.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
        (
            "Runtime and UI effects",
            "Ghostty config options that affect app, renderer, input, font, terminal, and platform behavior produce equivalent runtime effects.",
            "Roastty runtime/UI effects are not yet fully proven for all config-affecting options.",
            "Gap",
            "Focused runtime and GUI parity experiments are required.",
            "`issues/0805-roastty-ghostty-parity/config-matrix.md`; `issues/0805-roastty-ghostty-parity/walkthrough-matrix.md`",
            "Tier 3",
            "TBD by future runtime/GUI config parity experiments.",
            "Before closing Issue 805.",
            "Static and unit config guards cannot prove visible app behavior.",
            "Experiment 12",
            "Unresolved config facet.",
        ),
    ]
    return [
        (
            f"| CFG-{start_id + index:03d} | {name} | {upstream} | {roastty} "
            f"| {status} | {method} | {evidence} | {tier} | {guard} | {cadence} "
            f"| {sufficiency} | {owner} | {notes} |\n"
        )
        for index, (
            name,
            upstream,
            roastty,
            status,
            method,
            evidence,
            tier,
            guard,
            cadence,
            sufficiency,
            owner,
            notes,
        ) in enumerate(rows)
    ]


def emit_matrix(inventory: Inventory, matrix: Path) -> None:
    header = """# Config Matrix

This matrix tracks Ghostty configuration option parity, config-file behavior,
defaults, diagnostics, precedence, formatting, and runtime effects.

## Row Schema

| Column | Meaning |
| --- | --- |
| ID | Stable row ID, prefixed `CFG-`. |
| Config behavior / option | Option, parser rule, default, diagnostic, precedence rule, or runtime effect. |
| Upstream behavior / source | Ghostty behavior and source path or user config path. |
| Roastty behavior / path | Roastty behavior and source path or user config path. |
| Status | `Pass`, `Gap`, `Intentional divergence`, or `Not applicable`. |
| Verification method | Concrete command, unit test, integration test, or walkthrough. |
| Evidence artifact | Log, test output, screenshot, or matrix row proving the status. |
| Guard tier | Tier 0-4 from the Issue 805 regression guard policy. |
| Guard command / checklist | Exact command or manual checklist that catches regressions. |
| Run cadence | When the guard should run. |
| Guard sufficiency | Why this guard is strong enough for the row. |
| Owner experiment | Experiment that created or last updated the row. |
| Notes | Short context, if needed. |

## Rows

| ID | Config behavior / option | Upstream behavior / source | Roastty behavior / path | Status | Verification method | Evidence artifact | Guard tier | Guard command / checklist | Run cadence | Guard sufficiency | Owner experiment | Notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| CFG-001 | Baseline user config file path | Ghostty user config is `~/.config/ghostty/config`. | Roastty analogous user config is `~/.config/roastty/config`. | Pass | Compare files before A/B runs without logging private config contents. | `logs/issue805-exp1-rerun-clean-baseline.log` line `CONFIG_FILES_MATCH=yes`. | Tier 0 | `cmp -s ~/.config/ghostty/config ~/.config/roastty/config` | Before A/B visual or walkthrough experiments that depend on user config. | File equality is sufficient for the temporary baseline until per-option config parity is audited. | Experiment 1 | Later config experiments must replace this baseline with per-option rows. |
"""
    represented = set(inventory.represented)
    lines = [header]
    row_id = 2
    for option in inventory.upstream:
        if option in represented:
            status = "Pass"
            notes = "Inventory/default-surface coverage only; behavior facets are tracked separately."
        else:
            status = "Gap"
            notes = "Missing from Roastty documented config option inventory."
        lines.append(matrix_row(row_id, option, status, notes))
        row_id += 1
    for alias in inventory.aliases:
        lines.append(alias_row(row_id, alias))
        row_id += 1
    lines.extend(default_and_facet_rows(row_id))
    matrix.write_text("".join(lines))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument("--roastty", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--matrix", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    upstream, aliases, internal = extract_ghostty(args.upstream)
    inventory = Inventory(
        upstream=upstream,
        aliases=aliases,
        internal=internal,
        roastty=extract_roastty(args.roastty),
    )
    emit_inventory(inventory, args.output)
    if args.matrix is not None:
        emit_matrix(inventory, args.matrix)

    print(f"ghostty_canonical={len(inventory.upstream)}")
    print(f"ghostty_aliases={len(inventory.aliases)}")
    print(f"ghostty_internal={len(inventory.internal)}")
    print(f"roastty={len(inventory.roastty)}")
    print(f"represented={len(inventory.represented)}")
    print(f"missing={len(inventory.missing)}")
    print(f"extra={len(inventory.extra)}")


if __name__ == "__main__":
    main()
