#!/usr/bin/env python3
"""Inventory pinned Ghostty and Roastty config option names.

This is intentionally a bounded source extractor, not a general Zig or Rust
parser. It only reads the source regions relevant to Issue 805 Experiment 6:
Ghostty's top-level Config fields, Ghostty's compatibility map, and Roastty's
pub(crate) Config fields.
"""

from __future__ import annotations

import argparse
import dataclasses
import re
from pathlib import Path


FIELD_RE = re.compile(r'^(?P<name>@"[^"]+"|[A-Za-z_][A-Za-z0-9_]*):')
ALIAS_RE = re.compile(r'^\s*\.\{\s*"(?P<alias>[^"]+)"\s*,')
RUST_DOC_KEY_RE = re.compile(r"^\s*/// `(?P<key>[^`]+)`\.")
RUST_FIELD_RE = re.compile(r"^\s*pub\s+(?P<field>[A-Za-z_][A-Za-z0-9_]*)\s*:")


@dataclasses.dataclass(frozen=True)
class Inventory:
    upstream: list[str]
    aliases: list[str]
    internal: list[str]
    roastty: list[str]

    @property
    def missing(self) -> list[str]:
        return sorted(set(self.upstream) - set(self.roastty))

    @property
    def extra(self) -> list[str]:
        return sorted(set(self.roastty) - set(self.upstream))

    @property
    def represented(self) -> list[str]:
        return sorted(set(self.upstream) & set(self.roastty))


def normalize_zig_field(raw: str) -> str:
    if raw.startswith('@"') and raw.endswith('"'):
        return raw[2:-1]
    return raw.replace("_", "-")


def extract_ghostty(path: Path) -> tuple[list[str], list[str], list[str]]:
    aliases: list[str] = []
    fields: list[str] = []
    internal: list[str] = []
    in_compatibility = False
    in_config_fields = False

    for line in path.read_text().splitlines():
        if line.startswith("pub const compatibility"):
            in_compatibility = True
            continue

        if in_compatibility:
            match = ALIAS_RE.match(line)
            if match:
                aliases.append(match.group("alias"))
                continue
            if line.startswith("});"):
                in_compatibility = False
                in_config_fields = True
                continue
            continue

        if in_config_fields and line.startswith("pub fn "):
            break

        if not in_config_fields:
            continue

        match = FIELD_RE.match(line)
        if not match:
            continue

        raw = match.group("name")
        name = normalize_zig_field(raw)
        if raw.startswith("_") or name.startswith("_"):
            internal.append(raw if raw.startswith("_") else name)
            continue
        fields.append(name)

    return sorted(set(fields)), sorted(set(aliases)), sorted(set(internal))


def extract_roastty(path: Path) -> list[str]:
    keys: list[str] = []
    pending_docs: list[str] = []
    in_config = False
    depth = 0

    for line in path.read_text().splitlines():
        if line.startswith("pub(crate) struct Config {"):
            in_config = True
            depth = 1
            continue

        if not in_config:
            continue

        depth += line.count("{") - line.count("}")
        if depth <= 0:
            break

        doc_match = RUST_DOC_KEY_RE.match(line)
        if doc_match:
            pending_docs.append(doc_match.group("key"))
            continue

        if RUST_FIELD_RE.match(line) and pending_docs:
            keys.extend(pending_docs)
            pending_docs = []
            continue

        if line.strip() and not line.strip().startswith("///"):
            pending_docs = []

    return sorted(set(keys))


def markdown_list(values: list[str]) -> str:
    if not values:
        return "- None.\n"
    return "\n".join(f"- `{value}`" for value in values) + "\n"


def emit_inventory(inventory: Inventory, output: Path) -> None:
    content = f"""# Config Inventory

Generated by `issues/0805-roastty-ghostty-parity/config_inventory.py` for
Issue 805 Experiment 6.

## Counts

| Category | Count |
| --- | ---: |
| Ghostty canonical config options | {len(inventory.upstream)} |
| Ghostty compatibility aliases | {len(inventory.aliases)} |
| Ghostty private/internal fields | {len(inventory.internal)} |
| Roastty documented config options | {len(inventory.roastty)} |
| Canonical options represented by Roastty | {len(inventory.represented)} |
| Canonical options missing from Roastty | {len(inventory.missing)} |
| Roastty-only options | {len(inventory.extra)} |

## Extraction Boundaries

- Upstream canonical options are top-level fields in
  `vendor/ghostty/src/config/Config.zig` after `pub const compatibility` and
  before the first `pub fn`.
- Compatibility aliases are entries in Ghostty's static `compatibility` map.
- Private/internal Ghostty fields are counted for audit completeness but are not
  user config options.
- Roastty options are documented field keys in
  `roastty/src/config/mod.rs` inside `pub(crate) struct Config`.

## Ghostty Canonical Options

{markdown_list(inventory.upstream)}
## Ghostty Compatibility Aliases

{markdown_list(inventory.aliases)}
## Ghostty Private/Internal Fields

{markdown_list(inventory.internal)}
## Roastty Options

{markdown_list(inventory.roastty)}
## Missing Canonical Options

{markdown_list(inventory.missing)}
## Roastty-Only Options

{markdown_list(inventory.extra)}
## Classification Notes

- All represented canonical options remain `Gap` in `config-matrix.md` until a
  later experiment proves defaults, parser behavior, formatting, diagnostics,
  precedence, and runtime effect where applicable.
- Missing canonical options are `Gap`.
- Compatibility aliases are `Gap` until a later experiment proves parsing and
  compatibility semantics.
- Private/internal Ghostty fields are not ordinary user config options and do
  not receive config matrix rows in this experiment.
"""
    output.write_text(content)


def matrix_row(row_id: int, option: str, status: str, notes: str) -> str:
    return (
        f"| CFG-{row_id:03d} | `{option}` | Ghostty canonical config option "
        f"`{option}` in `vendor/ghostty/src/config/Config.zig`. | Roastty "
        f"documented config option inventory from `roastty/src/config/mod.rs`. "
        f"| {status} | Static inventory only; behavior is not proven by this "
        f"experiment. | `issues/0805-roastty-ghostty-parity/config-inventory.md` "
        f"| Tier 0 | `python3 issues/0805-roastty-ghostty-parity/config_inventory.py "
        f"--upstream vendor/ghostty/src/config/Config.zig --roastty "
        f"roastty/src/config/mod.rs --output "
        f"issues/0805-roastty-ghostty-parity/config-inventory.md --matrix "
        f"issues/0805-roastty-ghostty-parity/config-matrix.md` | When config "
        f"fields change or before closing Issue 805. | Static inventory catches "
        f"name coverage drift; later tests must prove semantics. | Experiment 6 "
        f"| {notes} |\n"
    )


def alias_row(row_id: int, alias: str) -> str:
    return (
        f"| CFG-{row_id:03d} | compatibility alias `{alias}` | Ghostty "
        f"compatibility alias `{alias}` in `vendor/ghostty/src/config/Config.zig`. "
        f"| Roastty compatibility alias behavior is not proven by this "
        f"experiment. | Gap | Static inventory only; alias parser behavior is "
        f"not proven by this experiment. | "
        f"`issues/0805-roastty-ghostty-parity/config-inventory.md` | Tier 0 | "
        f"`python3 issues/0805-roastty-ghostty-parity/config_inventory.py "
        f"--upstream vendor/ghostty/src/config/Config.zig --roastty "
        f"roastty/src/config/mod.rs --output "
        f"issues/0805-roastty-ghostty-parity/config-inventory.md --matrix "
        f"issues/0805-roastty-ghostty-parity/config-matrix.md` | When config "
        f"compatibility aliases change or before closing Issue 805. | Static "
        f"inventory catches alias drift; later parser tests must prove "
        f"semantics. | Experiment 6 | Compatibility alias remains unproven. |\n"
    )


def emit_matrix(inventory: Inventory, matrix: Path) -> None:
    header = """# Config Matrix

This matrix tracks Ghostty configuration option parity, config-file behavior,
defaults, diagnostics, precedence, formatting, and runtime effects.

## Row Schema

| Column | Meaning |
| --- | --- |
| ID | Stable row ID, prefixed `CFG-`. |
| Config behavior / option | Option, parser rule, default, diagnostic, precedence rule, or runtime effect. |
| Upstream behavior / source | Ghostty behavior and source path or user config path. |
| Roastty behavior / path | Roastty behavior and source path or user config path. |
| Status | `Pass`, `Gap`, `Intentional divergence`, or `Not applicable`. |
| Verification method | Concrete command, unit test, integration test, or walkthrough. |
| Evidence artifact | Log, test output, screenshot, or matrix row proving the status. |
| Guard tier | Tier 0-4 from the Issue 805 regression guard policy. |
| Guard command / checklist | Exact command or manual checklist that catches regressions. |
| Run cadence | When the guard should run. |
| Guard sufficiency | Why this guard is strong enough for the row. |
| Owner experiment | Experiment that created or last updated the row. |
| Notes | Short context, if needed. |

## Rows

| ID | Config behavior / option | Upstream behavior / source | Roastty behavior / path | Status | Verification method | Evidence artifact | Guard tier | Guard command / checklist | Run cadence | Guard sufficiency | Owner experiment | Notes |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| CFG-001 | Baseline user config file path | Ghostty user config is `~/.config/ghostty/config`. | Roastty analogous user config is `~/.config/roastty/config`. | Pass | Compare files before A/B runs without logging private config contents. | `logs/issue805-exp1-rerun-clean-baseline.log` line `CONFIG_FILES_MATCH=yes`. | Tier 0 | `cmp -s ~/.config/ghostty/config ~/.config/roastty/config` | Before A/B visual or walkthrough experiments that depend on user config. | File equality is sufficient for the temporary baseline until per-option config parity is audited. | Experiment 1 | Later config experiments must replace this baseline with per-option rows. |
"""
    represented = set(inventory.represented)
    lines = [header]
    row_id = 2
    for option in inventory.upstream:
        if option in represented:
            notes = "Name is represented, but behavior remains unproven."
        else:
            notes = "Missing from Roastty documented config option inventory."
        lines.append(matrix_row(row_id, option, "Gap", notes))
        row_id += 1
    for alias in inventory.aliases:
        lines.append(alias_row(row_id, alias))
        row_id += 1
    matrix.write_text("".join(lines))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument("--roastty", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--matrix", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    upstream, aliases, internal = extract_ghostty(args.upstream)
    inventory = Inventory(
        upstream=upstream,
        aliases=aliases,
        internal=internal,
        roastty=extract_roastty(args.roastty),
    )
    emit_inventory(inventory, args.output)
    if args.matrix is not None:
        emit_matrix(inventory, args.matrix)

    print(f"ghostty_canonical={len(inventory.upstream)}")
    print(f"ghostty_aliases={len(inventory.aliases)}")
    print(f"ghostty_internal={len(inventory.internal)}")
    print(f"roastty={len(inventory.roastty)}")
    print(f"represented={len(inventory.represented)}")
    print(f"missing={len(inventory.missing)}")
    print(f"extra={len(inventory.extra)}")


if __name__ == "__main__":
    main()
